### ISSUE TITLE
Checking absent wind direction entries crashes the utility

### ISSUE THREAD

**Issue by ArendPWS** [BobAtchley/weewx-ws6in1#1]
https://github.com/BobAtchley/weewx-ws6in1/blob/da0e783105a895bf0c589172e073ce7181286059/bin/user/csv_ws6in1#L143

When testing this new utility it crashed on absent wind direction entries. Expanding this code to:

if my_str == "--" or my_str == "---": 

fixed it.

This check for absent wind direction entries is also lacking in WS6in1.py.

**Comment by BobAtchley** [comment]
I have released version 0.8 of WS6in1 which includes the suggested fix.  This behaviour has not been seen from my weather station, but its early days and if this makes the WS6in1 more stable then we all benefit. 
Thanks for raising the issue

**Comment by ArendPWS** [comment]
Hello Bob,

I suspect behaviour is related to the way the console is configured. If one
chooses to display numerical wind directions there might be no problem. I
have mine configured to display cardinals and it only crashed on
missing/faulty entries,

Op di 23 jun. 2020 om 22:49 schreef BobAtchley <notifications@github.com>:
