### ISSUE TITLE
Bad crc when dumping data with csv tool or when backfilling on weewx startup

### ISSUE THREAD

**Issue by bartdevriendt** [BobAtchley/weewx-ws6in1#13]
I had a problem this week with weewx not fetching data from my Garni 935PC console.  After restarting I tried to backfill but I get a lot of warnings:

WARNING user.ws6in1: genStartupRecords: bad CRC

When dumping data from the console with the csv tool the same:

WARNING: gen_startup_records: bad CRC

Also the csv file I created only contains data until july of this year while my database has records until 22/9.  

I have no I idea if this is normal or not

**Comment by BobAtchley** [comment]
The 'bad CRC' is a warning not an error.  What has happened is that when weewx/ws6in1 fetches the data occasionally the weather station console is busy and it doesn't form the data properly.  When this happens the checksum (CRC) does not match the data in the message.  WS6in1 always checks that the CRC matches the data.  If it does all is well, if it doesn't it raises the 'bad CRC' warning, but then fetches the same data again.  When backfilling data where there are multiple days worth of data to fetch then it is quite common to see these warnings, but the data will always be correctly read
