### ISSUE TITLE
find_my_device: dev not found

### ISSUE THREAD

**Issue by ar0berts** [BobAtchley/weewx-ws6in1#6]
I'm probably doing something crass! - But...

I have an SDR Doingle: `Bus 003 Device 007: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T`
It collects data from the Bresser 6 in 1 with: `rtl_433 -X bresser:FSK_PCM:29:29:2969 -f 868290000 -s 1024000`

but if I stop weewx and run `andrew@andrew-Plasma-Laptop:~/.weewx/weewx-ws6in1/bin/user$ sudo python3 ./csv_ws6in1`
I get 
`CSV output file: ws6in1_2020-09-08-09-50-09.csv
Raw output file: ws6in1_2020-09-08-09-50-09.raw
gen_startup_records: starting archive loop ...
CRITICAL: find_my_device: dev not found
`
likewise if I run weewxd I get:
`andrew@andrew-Plasma-Laptop:~$ sudo weewxd
Traceback (most recent call last):
  File "/usr/share/weewx/weewxd", line 261, in <module>
    main()
  File "/usr/share/weewx/weewxd", line 154, in main
    engine.run()
  File "/usr/share/weewx/weewx/engine.py", line 158, in run
    self.dispatchEvent(weewx.Event(weewx.STARTUP))
  File "/usr/share/weewx/weewx/engine.py", line 224, in dispatchEvent
    callback(event)
  File "/usr/share/weewx/weewx/engine.py", line 530, in startup
    self._catchup(self.engine.console.genStartupRecords)
  File "/usr/share/weewx/weewx/engine.py", line 638, in _catchup
    for record in generator(lastgood_ts):
  File "/usr/share/weewx/user/ws6in1.py", line 1122, in genStartupRecords
    self.find_my_device()
  File "/usr/share/weewx/user/ws6in1.py", line 836, in find_my_device
    raise ValueError('Device not found')
ValueError: Device not found`

I unplugged the dongle and re-inserted it to make sure there wasn't some usb-claim conflict that would prevent the device being recognised. The code line 832 in ws6in1.py:
`
        self.dev = usb.core.find(idVendor=self.vendor, idProduct=self.product)
`
is apparently not accessing 0bda as the idVendor and or 2838 as the idProduct. 

Any clues as to where to go next?

Andrew

**Comment by BobAtchley** [comment]
Hi Andrew,

Can I check you have a compatible Bresser it should be this one:
https://www.bresseruk.com/bresser-pc-weather-station-with-6-in-1-outdoor-sensor.html

This provides a dedicated usb link to a 'PC'.  I suspect you have the 'WiFi' version - the usb connection that that provides does not provide an API that can be used by weewx (not sure but I think its power only).

If you do have a compatible version, please try changing the usb cable.  Some people have had problems with usb hubs (although I am using one without any issues).  The error you are getting is basically that the driver cannot communicate with the Bresser console, so is a show stopper.

Regards

Bob

**Comment by ar0berts** [comment]
Ahh Bob, - I'm dead in the water then!

Yes - the one I have has a radio link from the station to the console and the console then links to the network via wifi with a console USB port that, as you say, is power only. Sad that Bresser are not more open as it should be possible to interrogate the console over the network but they've not released any code to enable that. The product is also only seems to export to Wunderground.com and since that has become commercial you can't download your data from there either!

Thanks for your help.

Andrew
