### ISSUE TITLE
ModuleNotFoundError: No module named 'crcmod'

### ISSUE THREAD

**Issue by PeterHurn** [BobAtchley/weewx-ws6in1#7]
Hi,

I have just purchased a Bresser 6 in 1 7002570 Weather Station.

I followed the instruction using Python 3 and pip3, so "pip3 install crcmod"

After I enter "sudo wee_config --reconfigure" I complete the station information then see the station options as follows:

Installed drivers include:
  0) ?               (user.ws6in1)             No module named 'crcmod'
  1) AcuRite         (weewx.drivers.acurite)

....

After selecting 0 and entering the station information I receive the following:

Traceback (most recent call last):
  File "/usr/share/weewx/wee_config", line 123, in <module>
    main()
  File "/usr/share/weewx/wee_config", line 117, in main
    config_mgr.run(args, options)
  File "/usr/share/weewx/weecfg/config.py", line 114, in run
    stn_info = self.get_stn_info(config_dict, options)
  File "/usr/share/weewx/weecfg/config.py", line 155, in get_stn_info
    stn_info.update(weecfg.prompt_for_driver_settings(driver, config_dict))
  File "/usr/share/weewx/weecfg/__init__.py", line 1685, in prompt_for_driver_settings
    __import__(driver)
  File "/usr/share/weewx/user/ws6in1.py", line 369, in <module>
    import crcmod
ModuleNotFoundError: No module named 'crcmod'

Any help gratefully received.

Peter.

**Comment by ideosky** [comment]
Hi Peter,

I had the same problem, i fixed it by reinstalling crcmod as su.

Sudo su
pip3 install crcmod

Then I rebooted and started the weewx service.

Everything is working fine now for almost 3 months already

Sincerely,

Guy
⁣Verzonden door BlueMail ​

Op 4 nov. 2020 10:19, om 10:19, Peter Hurn <notifications@github.com> schreef:

**Comment by BobAtchley** [comment]
Hi Peter,

I recently reinstalled weewx and the WS6in1 driver on a RaspberryPi 4 (previously on a rPi 2) and hit the same problem
I solved it by installing the crcmod library via the apt command:

$ sudo apt install python3-crcmod

Not sure why the pip3 command didn't provide the needed files, this wasn't needed originally.

I am in the process of updating the readme.txt to add this and focus on python3 installation.
As the driver seems stable I'm also going to up it to version 1.0 (but no code changes from 0.9 other than changing the version number)

Hope this helps

Bob

**Comment by PeterHurn** [comment]
Thank you Bob and Guy, that seems to have resolved the installation of the the crcmod.

Now on to testing 👍

**Comment by PeterHurn** [comment]
Issue closed.
