### ISSUE TITLE
[WS6in1] WeeWX doesn't generate records when main outdoor is offline

### ISSUE THREAD

**Issue by ArendPWS** [BobAtchley/weewx-ws6in1#9]
Hi Bob,

I don't know at the moment if this is a WeeWX issue or that it is caused by the WS6in1 driver. A few days ago my main outdoor unit stopt working (had to replace the batteries). After everything was back up and running, I noticed that there was data missing in my charts for the period the outdoor unit was offline. That is ok for the data measured by the outdoor unit. But I found out that there were no WeeWX records at all in the database for the period the outdoor unit was offline. This can't be right, because the console still functions without main outdoor unit measuring: indoor temperature, indoor humidity, pressure and in my case temperature and humidity from an extra sensor. I have checked the memory (datalogger) of the console (using your utility) and all these aforementioned measurements are present in memory (datalogger). Trying to catchup (genStartupRecords) made no difference. Maybe you can replicate this issue and see what happens?

I am using WS6in1 version 1.02 at the moment.

Kind regards,

Arend

**Comment by BobAtchley** [comment]
Hi Arend,

The batteries on my unit failed a few months ago, but fortunately it was intermittent failure and I was able to replace the batteries before complete failure - I didn't notice the errors you have experienced (the annoying thing is each month I reset the console data and check if there is any low battery indicator - there wasn't but the batteries failed only a few days later).

As you say even if not receiving external data the console should still record internal data (pressure, indoor temperature and humidity) and extra sensors.  So I strongly suspect this is a WS6in1 error.  Probably what is happening is it's getting unexpected readings (as there are none) and rejecting the console message.  I would need to experiment to find out (may be this weekend).

Could you check your equivalent of /var/log/syslog for weewx errors and warnings for the period your batteries had failed and if there are any paste them here

Thanks

Bob

**Comment by ArendPWS** [comment]
> The batteries on my unit failed a few months ago, but fortunately it was intermittent failure and I was able to replace the batteries before complete failure - I didn't notice the errors you have experienced (the annoying thing is each month I reset the console data and check if there is any low battery indicator - there wasn't but the batteries failed only a few days later).

I experienced the same with the battery status indicator in the past. It seems to be quite useless in that it doesn't give you enough time to anticapate (design flaw I guess).
 
> As you say even if not receiving external data the console should still record internal data (pressure, indoor temperature and humidity) and extra sensors. So I strongly suspect this is a WS6in1 error. Probably what is happening is it's getting unexpected readings (as there are none) and rejecting the console message. I would need to experiment to find out (may be this weekend).

I figured out why there weren't any new additions to the WeeWX database. This was caused by failure of an XType I use that depends on both the outside temperature from the main unit and outside temperature from the extra sensor.

But the console kept registring the inside temperature/humidity (console), pressure (console) and temperature/humidity of my extra sensor as you can see in this log dump from the console memory:

![Voorbeeld missende data weerstation](https://user-images.githubusercontent.com/67259651/109201646-60f4df00-77a2-11eb-816b-3e783ebff9ff.png)

The question now is why WeeWX isn't retreiving the valid records from the memory of the console on restart with catchup enabled? Somehow these items (from epoch 1613944500 upto 1613977500) from the console memory aren't offered by the ws6in1 driver or get rejected by WeeWX?

**Comment by BobAtchley** [comment]
OK that's more understandable.  Weewx isn't back-filling  because its got later records (from when the new batteries went in), it only back-fills from the time of the last database record to current time.  Weewx has an import tool (which I have used to import records from my old weather station) which I think you can use to fill in the gaps

**Comment by ArendPWS** [comment]
> OK that's more understandable. Weewx isn't back-filling because its got later records (from when the new batteries went in), it only back-fills from the time of the last database record to current time. Weewx has an import tool (which I have used to import records from my old weather station) which I think you can use to fill in the gaps

I wrongly presumed that WeeWX would take care of filling in the gaps (there surely will be a reason why this hasn't been implemented). Have added the missing records now with wee_import, looks fine.

One more remark about battery consumption of the outdoor main unit. I get the impression that the batteries last for about three months, a bit short I believe. Have plans to connect the outdoor unit to a power adapter so changing batteries should be history from that moment on.

Thanks for your time and help Bob,

Arend
